global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Monitorowanie samego Prometheusa
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitorowanie Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Monitorowanie cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Monitorowanie kontenerów Docker
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # Włącz metryki Dockera
  #  - job_name: 'docker'
  #    static_configs:
  #      - targets: ['host.docker.internal:9323', 'docker-host:9323']
  #    metrics_path: /metrics
